name: build-ios
on: 
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:
env:
  targetName: stellarium
jobs:
  build:
    name: Build
    runs-on: macos-10.15
    strategy:
      matrix:
        #qt_ver: [5.12.10, 5.15.2]
        qt_ver: [5.15.2]
        qt_target: [ios]
    steps:
      - name: Install Qt
        # if: steps.cacheqt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.10.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ios
        run: |
          qmake -r -spec macx-ios-clang CONFIG+=release CONFIG+=iphoneos
          make
          ls

      #- name: artifacts
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: ios.zip
      #    path: Release-iphonesimulator/${{ env.targetName }}.app

      - name: Packing
        run: |
          mkdir Payload
          cp -R Release-iphonesimulator/${{ env.targetName }}.app Payload/
          zip -q -r ${{ env.targetName }}.zip Payload
          mv ${{ env.targetName }}.zip ${{ env.targetName }}.ipa
          ls -l

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-packed.ipa
          path: ${{ env.targetName }}.ipa