name: build-windows-msvc
on:
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

env:
  targetName: stellariumMobile

jobs:
  Build-MSVC:
    name: Build-MSVC
    runs-on: windows-latest
    strategy:
      matrix:
        qt_ver: [5.15.1]
        qt_target: [desktop]
        qt_arch: [win64_msvc2019_64, win32_msvc2019]
        include:
          - qt_arch: win64_msvc2019_64
            msvc_arch: x64
            output_arch: x86_64
            qt_arch_install: msvc2019_64
          - qt_arch: win32_msvc2019
            msvc_arch: x86
            output_arch: x86
            qt_arch_install: msvc2019
    
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          target: ${{ matrix.qt_target }}
          arch: ${{ matrix.qt_arch }}
          modules: qtwebengine
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
          
      - name: build-msvc
        shell: cmd
        env:
          vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ..\${{ env.targetName }}.pro
          nmake
          cd ..
          
      - name: package
        shell: cmd
        run: |
          windeployqt build\release\${{ env.targetName }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}
          path: build\release
